# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ff180b8dcc358a20a58f67deb382ed58701ecd6dddf77f3a7a9fd64ed45ddfaced01d53a14cee05d187434ce8292aece9f1376b40f8d7901b40c11519765ca

test:
  secret_key_base: 404499a0ee4b38d9cfb60ced400346cd920c8951ebfaecc6406412768a09d310648cd995c6823573e2e34a3781bf6dcbf90d248e790f234d12c6b9247866fbca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
